server:
  port: 9001
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://boccu.cemjnnwtaor1.us-west-2.rds.amazonaws.com:3306/final_project?serverTimezone=Aisa/Seoul
    username: boccu
    password: 12341234
    
#mybatis
mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml


